### ISSUE TITLE
7/25(月)　本日やること

### ISSUE THREAD

**Issue by yui0118** [yui0118/MyToDo#12]
## Tasks
- [x] ReactとNext.jsの実装の仕方が少し異なるので、Next.jsの実装の仕方を身につける
  - [x] [入門者は基礎からしっかり理解Next.jsの基本(React)](https://reffect.co.jp/react/next-js)(50%達成)
  - [x] [Next.jsを利用した初めての本格的Markdownブログサイトの構築](https://reffect.co.jp/react/nextjs-markdown-blog)
