### ISSUE TITLE
7/26(火)　本日やること

### ISSUE THREAD

**Issue by yui0118** [yui0118/MyToDo#13]
## Tasks
- [x] 昨日の続きで、ReactとNext.jsの実装の仕方が少し異なるため、Next.jsの実装の仕方を身につける
  - [x] [入門者は基礎からしっかり理解Next.jsの基本(React)](https://reffect.co.jp/react/next-js)
  - [x] [Next.jsを利用した初めての本格的Markdownブログサイトの構築](https://reffect.co.jp/react/nextjs-markdown-blog)
