### ISSUE TITLE
7/29(金)　本日やること

### ISSUE THREAD

**Issue by yui0118** [yui0118/MyToDo#16]
## Tasks

- [ ] PF
  - [ ] 目標入力フォームを`React-hook-form`を使って、書き直す。
- [ ] [techpit](【Rails×React】UberEats風アプリを作りながら、SPA開発を学ぼう)
  - [ ] 5章 : レストラン一覧ページを作る
    - [ ] 5-1:styled-componentとCSS in JSについて
    - [ ] 5-2:レストラン一覧ページのヘッダーを作る
    - [ ] 5-3:useState, useReducerの解説
    - [ ] 5-4:reducerを作成する
    - [ ] 5-5:APIのデータを画面に表示する
    - [ ] 5-6:レストラン一覧ページを完成させる
    - [ ] 5-7:最後の一手間！+ React Developer Toolsの紹介
