### ISSUE TITLE
7/14(木)　本日やること

### ISSUE THREAD

**Issue by yui0118** [yui0118/MyToDo#2]
## Tasks
- [x]  Bye Bye garbage
    - [x]  GitHubにissueを書き出す(残り1/3)(7/14までに終わらせる)(0:40)
- [x]  課題
    - [x]  React発展 6(7/14までに終わらせる)(3:30)
    - [x]  ポートフォリオの仕様を考えて、Notionにまとめる(7/15まで)(1:05)(30%完了)
      - [x] どんな機能を持たせるか
      - [x] どんな画面にするのか
      - [x] 何ができる作品にするのか
