### ISSUE TITLE
8/5(金) 本日やること

### ISSUE THREAD

**Issue by yui0118** [yui0118/MyToDo#21]
## Tasks
- [x] [Mantine UI (React コンポーネントライブラリ) The Complete Guide](https://www.udemy.com/course/mantine-react-complete-guide-nextjs/)
  - [x] Group
  - [x] Grid
  - [x] useForm with Yup validation
  - [x] Menu + RadioGroup + MultiSelect + TransferList
