### ISSUE TITLE
7/17(日) 本日やること

### ISSUE THREAD

**Issue by yui0118** [yui0118/MyToDo#4]
## Tasks
- [ ]  Bye Bye garbage
    - [ ]  [issue#1](https://github.com/yui0118/bye_bye_garbage/issues/1)(7/19〆切)
      - [ ] どんなテーブルが必要か明確にする
      - [ ] テーブルごとにどんなカラムが必要か明確にする
      - [ ] 正規化をして、テーブルの分割を行う
      - [ ]  ER図を作成して、テーブル間の関係を分かりやすくする
        - [ ] draw.ioの使い方を調べる(参考記事を下に列挙)
            - [ ] https://e-seventh.com/draw-io-er-diagram/
            - [ ] https://zenn.dev/kumamoto/scraps/2f94a539f80b89
