### ISSUE TITLE
7/19(火)　本日やること

### ISSUE THREAD

**Issue by yui0118** [yui0118/MyToDo#6]
## Tasks
- [x]  Bye Bye garbage
    - [x]  [issue#1](https://github.com/yui0118/bye_bye_garbage/issues/1)(7/19〆切)
      - [x] どんなテーブルが必要か明確にする
      - [x] テーブルごとにどんなカラムが必要か明確にする
      - [x] 正規化をして、テーブルの分割を行う
      - [x]  ER図を作成して、テーブル間の関係を分かりやすくする
        - [x] draw.ioの使い方を調べる(参考記事を下に列挙)
            - [x] https://e-seventh.com/draw-io-er-diagram/
            - [x] https://zenn.dev/kumamoto/scraps/2f94a539f80b89
