### ISSUE TITLE
7/21(木)　本日やること

### ISSUE THREAD

**Issue by yui0118** [yui0118/MyToDo#8]
## Tasks
- [x] 課題
  - [x] 実装したいことをタスクとして、洗い出し、issueに書き出す
  - [x] [Vercelでデプロイする](https://github.com/yui0118/piggy_bank/issues/4)
  - [x] [Pull RequestのテンプレートとIssueのテンプレートを用意する](https://github.com/yui0118/piggy_bank/issues/5)
