### ISSUE TITLE
7/22(金)　本日やること

### ISSUE THREAD

**Issue by yui0118** [yui0118/MyToDo#9]
## Tasks
- [x] 課題
  - [x] [topページを作成する](https://github.com/yui0118/piggy_bank/issues/6)
    - [x] useStateを使って表示を変えるためのstateを用意し、stateの値によって、目標を1個以上登録している場合と登録していない場合の表示を変えるように実装する
    - [ ] havingGoals stateがtrueの場合、目標がリスト形式で表示されるようにする　=> 目標を入力するフォームをまだ作成できていないので、今後のissueとして切り出すことにします。
    - [x] havingGoals stateがfalseの場合、「アプリ名・トップ画像・目標を入力ボタン」を表示されるようにする

**Comment by yui0118** [comment]
topページを実装するという課題でしたが、実装を行っていく過程で、様々な課題が出てきたので、他のissueとして切り出す予定のものを以下に記載する。
## 今後の課題
- フォームとして入力したデータをどのように保持し、かつ異なるコンポーネントにそのデータを渡すように実装するのか
- 表示分けの部分をコンポーネントとして切り出す場合、コンポーネントのファイル・ディレクトリ構成をどうするのか
- 表示分けの部分をコンポーネントとして切り出した場合に、表示分けの基準となるstateとstate更新関数をコンポーネント間でどのように受け渡すのか
